services:
  # Single service that serves both frontend and backend
  - type: web
    name: sonex-voicecraft
    env: node
    buildCommand: |
      # Copy root-package.json to package.json
      cp root-package.json package.json
      # Install dependencies
      npm install
      # Build frontend
      npm run build
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
